- batcontrol.py
- config/batcontrol_config_dummy.yaml
- dynamictariff/dynamictariff.py
- dynamictariff/evcc.py
Mache es möglich die Preisdaten von einer laufenden EVCC Instanz abzuholen. Damit arbeiten dann beide Prozesse immer auf der selben Datenbasis.
Getestet im Modultest und mit einem Dummy-Wechselrichter-Modul.
Wenn ich noch etwas anpassen muss, lass es mich wissen.
> Dyntariff evcc

- inverter/fronius.py
Creates get_powerunit_config in FroniusWR class, checks whether back up power is enabled and modifies minimum SoC used for calculations.
Fixes https://github.com/muexxl/batcontrol/issues/28
> Backup power

- batcontrol.py
> Improve type handling on charge rate

- batcontrol.py
- dynamictariff/awattar.py
- dynamictariff/baseclass.py
- dynamictariff/dynamictariff.py
- dynamictariff/evcc.py
- dynamictariff/tibber.py
- forecastconsumption/forecastconsumption.py
- forecastsolar/forecastsolar.py
- inverter/baseclass.py
- inverter/fronius.py
- inverter/inverter.py
- inverter/testdriver.py
- logfilelimiter/logfilelimiter.py
- mqtt_api.py
Aufgrund einiger kürzlicher Fehler (meinerseitz), arbeite mich mich durch die CodeQuality Checks von pylint durch, um mittelfristig die Code Qualität zu steigern.
Das waren jetzt die ersten Maßnahmen rund um Whitespaces, Zeilenlänge und Import Order.
Ich hatte pylint als github-Action in meinem Fork eingebaut und das failed horribly, weil wir da einiges non-standard Stellen haben.
> Pylint improvements

- batcontrol.py
Fixes https://github.com/muexxl/batcontrol/issues/35
as described in my comment there
> Recharge calc amendments to fix #35

- batcontrol.py
> Lock evaluation to full minutes

- batcontrol.py
- forecastconsumption/forecastconsumption.py
Next batch of changes and improvements.
Still needs some more testing
> Pylint improvements 4

- batcontrol.py
- config/batcontrol_config_dummy.yaml
- evcc_api.py
- mqtt_api.py
First implementation is running now for testing in my environment.
> Evcc connection

- batcontrol.py
- config/batcontrol_config_dummy.yaml
- Default logfile path is now inside "logs"
- File logging can be disabled
- Created default path "logs" in repository
Closed #45
> Rework of logging part-1

- batcontrol.py
Avoid a low watt recharging, which only negotiates batteries self discharge.
Closes #68
> Add a minimum charge rate of 500W

- forecastsolar/forecastsolar.py
Work longer with cached data over directly aborting the operation.
> forecastsolar api work longer with cached data

- config/batcontrol_config_dummy.yaml
- evcc_api.py
- mqtt_api.py
> EVCC : Enhance loadpoint configuration to support multiple topics

- HOWITWORKS.md
- README.MD
README.md and HOWITWORKS.md are updated to reflect the state of the software after my other PRs.
> Update to Documentation

- .github/workflows/pylint.yml
Instead of linting all files, 
- let Git Diff figure out all changed files 
- iterate over the files
-- lint each file
> Refactor pylint workflow to analyze only changed Python files

- batcontrol.py
- config/batcontrol_config_dummy.yaml
This PR introduces a new config section `a1_tuning`.
It allows some adjustments for expert users.
> Add options to tweak batcontrol behavior

- batcontrol.py
- config/batcontrol_config_dummy.yaml
- mqtt_api.py
Refers to #84  
Needs to be merged after algo tuning PR
> Dynamic price limit

- batcontrol.py
- inverter/fronius.py
Improve the internal send_request handling to have a better response to authentication issues:
#120
#113
> Fronius rework send_request and login handling

- src/batcontrol/__main__.py
- src/batcontrol/core.py
- src/batcontrol/dynamictariff/dynamictariff.py
- harmonize config reads
- Move checks for valid config to dedicated factory classes
- remove custom "use default" & check  functions
> Code Cleanups

- Dockerfile
This should fix the docker build pipeline by using prebuilt wheels for numpy and pandas
> Fix docker build pipeline

- .gitignore
- pyproject.toml
- src/batcontrol/inverter/fronius.py
> Adapt to Fronius URL changes with latest version

- src/batcontrol/__pkginfo__.py
This pull request includes a version update in the `src/batcontrol/__pkginfo__.py` file. The version has been incremented from `0.5.0dev` to `0.5.1dev` to reflect new changes or improvements.
> Fix version bump

- config/batcontrol_config.yaml.bpk
- config/batcontrol_config.yml.bkp
- config/batcontrol_config_dummy.yaml
- src/batcontrol/core.py
- src/batcontrol/logic/common.py
- src/batcontrol/logic/default.py
- src/batcontrol/logic/logic_interface.py
> feat: add minimum recharge amount and related logic for charging from grid
