muexxl/batcontrol

- batcontrol.py
- config/batcontrol_config_dummy.yaml
- dynamictariff/dynamictariff.py
- dynamictariff/evcc.py
- fronius/baseclass.py
- fronius/fronius.py
- fronius/inverter.py
- fronius/testdriver.py
Servus,
ohne Wechselrichter zu testen geht nicht, aber für bestimmte funktionen wäre es extrem hilfreich.
Mit dem PR wird die Funktionen der Fronius Klasse in einer allgemeine Inverter Klasse umgebaut. Direkter Zugriff auf Attribute wird auf Methoden gemappt.
Aktuell macht die Dummy-Klasse nichts weiter als ein paar statische Informationen zu liefern.
Angedacht war, dass man im auch das Lastprofil in die Klasse lädt und damit (zusammen im einer Varianz) die Rückmeldungen liefert. Aber so reicht es schonmal.
Bitte gebe mir Feedback wenn ich irgendwo noch etwas anpassen soll.
edit: Vorraussetzung ist der Merge vom EVCC PR (oder die Änderung hier nimmt das auch mit).
Liebe Grüße
Matthias
> Dummy Inverter Option

- batcontrol.py
- forecastconsumption/forecastconsumption.py
Before
```
2024-11-07 10:41:55 DEBUG [FC Cons] predicting consumption {0: 349.31066637990733, 1: 337.44065310859133, 2: 449.94174003422916, 3: 431.4012223906464, 4: 429.96383934717215, 5: 366.52213189636865, 6: 385.9124414911546, 7: 377.04416591312025, 8: 332.00330902738034, 9: 410.7293260535633, 10: 530.6202775056219, 11: 478.6638363088132, 12: 321.7042259195338, 13: 234.85612362430874}
```
After:
```
2024-11-07 10:54:30 DEBUG [FC Cons] predicting consumption: 349.31, 337.44, 449.94, 431.40, 429.96, 366.52, 385.91, 377.04, 332.00, 410.73, 530.62, 478.66, 321.70, 234.86
```
Same is true for 
-  Production FCST:
- Consumption FCST:
- Net Consumption FCST:
- Prices:
> Make Debug array values more readable

- batcontrol.py
- inverter/baseclass.py
- inverter/fronius.py
- mqtt_api.py
Both parameter did not relfect 1:1 against the reals SOC of the battery.
This resulted in a behavior, which was hard to explain.
We want to be have the user in focus  :-D .
With the PR, the values work against the designed capacity and follow the SOC% displayed everywhere.
I also fixed a bug resulting in a wrong "recharge OK" calculation.
> battery control parameter discharge limit & max charging seems unintuitive

- batcontrol.py
- dynamictariff/awattar.py
- dynamictariff/baseclass.py
- dynamictariff/dynamictariff.py
- dynamictariff/evcc.py
- dynamictariff/tibber.py
- forecastsolar/forecastsolar.py
Implements and closes https://github.com/muexxl/batcontrol/issues/63 and ensures the run is triggered on multiples of 3 minutes on the clock. (e.g. 03, 06, 09, 12, 15, 18, etc.)
To avoid API overload at the exact minute a delay of 15 seconds has been implemented.
The interval and the delay is currently not configurable, although maybe that would be wise to add to the config?
> Rewrite re-evaluation trigger every 3 minutes and add fixed offset of 15 secs

- inverter/fronius.py
Activates the Solar.API on login/initialisation of the Fronius inverter as this is required to read State of Charge and might not always be already activated by the end user.
Note this does not check the original status, nor saves and resets it back to what it was on closing batcontrol. I didn't think that was necessary.
> Set Fronius Solar.API to active on initialisation

- inverter/fronius.py
Currently this is set at every calculation, this is wholly uneccessary as the time of use limits are sufficient to achieve the intended behaviour. It is now set as a last step on initialisation, as this is needed to get intended behaviour if this was not set already by the user.
Configuration is reset to config prior to initialisation on script shut down as before.
> Set allow grid charging at the end of initialisation

- forecastsolar/forecastsolar.py
a HTTP 429 response is handled and the headers are consumed to understand when the next HTTP request is allowed.
This information is stored  as timestamp in an instance field
This instance field is then checked and respected in each periodic update
> Feature: handle FC solar rate limit errors

- config/batcontrol_config_dummy.yaml
- mqtt_api.py
handling connection errors for MQTT gracefully, attempting a configurable amount of retries in a configurable frequency
This is especially helpful when starting up multiple containers e.g. in a docker compose setup where the MQTT broker needs some boot time
> Add MQTT Connection retry

- Dockerfile
- README.MD
- entrypoint.sh
fixes #98 
- Configures the default timezone to `UTC` in the Dockerfile 
- Output the current local time and configured timezone in the `entrypoint.sh` script.
- Add `tzdata` package to `Dockerfile`
- default implementation in `logging.Formatter.converter` then uses `time.localtime` to create logging timestamps in local timezone
Timezone can be adjusted by passing in an override for TZ env var either in docker run or in docker-compose.yml
e.g. 
```
docker run -it --rm -e TZ=Europe/London batcontrol
```
> introduce proper OS-level timezone handling in Docker setup 

- .github/workflows/pylint.yml
- p.py
Modify the pylint workflow to output changed Python files as a space-separated list instead of a newline-separated list.
> gracefully handle multiple changed files

- config/batcontrol_config_dummy.yaml
- forecastsolar/fcsolar.py
As FCSolar and most other production forecast APIs use PVGIS as the underlying source, they pull horizon data from a single database. This reflects the ground level horizon but does not account for shading from trees or houses. 
This affects batcontrol if the array is shaded in the morning hours from a neighbouring house or trees.
This PR allows people to define their own horizon file according to these instructions: 
https://doc.forecast.solar/horizon
and here:
https://joint-research-centre.ec.europa.eu/photovoltaic-geographical-information-system-pvgis/getting-started-pvgis/pvgis-user-manual_en#ref-2-using-horizon-information
> Add query parameter to allow modification of horizon used to forecast PV production in fcsolar.py

- inverter/fronius.py
Closes 0.4.0  Login does not work below 1.35.4-1 #129
> Fronius: Less restrictive on missing auth header

- src/batcontrol/dynamictariff/evcc.py
The price field turned into the fieldname „value“.
> evcc-prices: adapt to API changes

- Dockerfile
This pull request updates the `Dockerfile` to improve the installation process for Python dependencies by ensuring binary packages are preferred during installation.
Key change:
* Updated the `RUN pip install` command in the `Dockerfile` to include the `--prefer-binary` flag, ensuring pip prioritizes binary packages when installing dependencies. This change may improve compatibility and reduce build times.
> Prefer-binary over source to always use piwheels even if source version is actually newer

- .github/workflows/pylint.yml
- pyproject.toml
This pull request updates the Python environment setup in the CI workflow to use the `uv` tool for improved dependency management and stability. It also introduces a configuration for `uv` in the `pyproject.toml` file.
* [`.github/workflows/pylint.yml`](diffhunk://#diff-3fb2867e4a7c0ecbfdf0f36a3078f1689dca17453c5e0ebdd0671bb94733b5a3L24-R39): Replaced `actions/setup-python@v3` with `astral-sh/setup-uv@v6` for setting up Python and managing dependencies. Enabled `activate-environment` for `uv` and updated commands to use `uv` for installing dependencies and running `pylint`. Added parallelism (`-j 0`) to `pylint` for performance improvements.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R28-R31): Added a `[tool.uv]` section to pin …
> Upgrade CI to use UV

- pyproject.toml
This pull request updates the dependency version for the `uv` tool in `pyproject.toml` to ensure compatibility with the latest features and improvements.
Dependency update:
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L31-R31): Updated the `required-version` for the `uv` tool from `~=0.6.0` to `~=0.7.0` to pin it to the latest major version for stability.
> Bump uv to version 0.7.0

- pyproject.toml
Fixes the warning: `SetuptoolsDeprecationWarning: project.license as a TOML table is deprecated`
Had the same error in another project, so I fixed it for batcontrol aswell :)
> Fix license error when building the package

- .github/workflows/prepare-release.yml
This pull request makes a small but important change to the GitHub Actions workflow file `.github/workflows/prepare-release.yml`. The change adds a `permissions` section to grant write access to repository contents, which is required for creating releases.
> Fix the failing release action

- config/batcontrol_config_dummy.yaml
The config-key had an unintended whitespace, which resulted into not a behavior of an unlimited PV charge.
This is already in the "field" from users relying on the dummy
config.
So this behavior is now reflectred with a fixed key entry and an uncommented line.
#163
> Fix the example value for max_pv_chage_rate

- src/batcontrol/evcc_api.py
Removed condition to store old max charge limit if it exceeds battery halt state of charge. This if results in discarding an old saved state. Without the condition, the parameter is stored once and then restored after charging.
Closes #171
> evcc-plugin: Fix for saving old charge_from_Grid vlaue
